# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'vnk' do
  pod 'AppCenter/Crashes', '~> 1.10.0'
  pod 'AppCenter/Analytics', '~> 1.10.0'
  pod 'AppCenterReactNativeShared', '~> 1.9.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Messaging', '~> 4.9.0'
  pod 'SwiftyJSON', '4.0.0'      
  pod 'Charts', '3.1.1'
  pod 'GoogleMaps', '~> 2.7.0'
  # Pods for vnk


end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.1'    # 4.0
    end
  end
end
